//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadoCrudMvcModels.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	
    
    public partial class Empleado
    {

        public int empleadoID { get; set; }

		[Required(ErrorMessage ="El Nombre es Obligatorio")]
        public string nombre { get; set; }

		[Required(ErrorMessage = "El Apellido es Obligatorio")]
		public string apellido { get; set; }

		[Required(ErrorMessage = "El Telefono es Obligatorio")]
		public string telefono { get; set; }

		[Required(ErrorMessage = "La Cedula es Obligatorio")]
		[MaxLength(ErrorMessage ="La Cedula tiene que tener Máximo 11 Caracteres")]
		public string cedula { get; set; }

        public Nullable<int> departamento { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
    }
}
